QA output created by 660

=== pmwebd default startup  ===
"context":
"context":

=== pmwebd security constraints, file service ===
PMWEBD error, XXX

PMWEBD error, XXX

* About to connect() to LOCALHOST port 44323 (####)
*   Trying LOCALADDR...
* Connected to LOCALHOST (LOCALADDR) port 44323 (####)
> GET /pmapi/2222/_fetch?names= HTTP/1.1
> User-Agent: FOO
> Host: LOCALHOST:44323
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Content-Length: 56
< Access-Control-Allow-Origin: *
< Content-Type: text/plain
< Date: DATE
<
{ [data not shown]
* Connection #### to host LOCALHOST left intact
PMWEBD error, XXX

PMWEBD error, XXX

* About to connect() to LOCALHOST port 44323 (####)
*   Trying LOCALADDR...
* Connected to LOCALHOST (LOCALADDR) port 44323 (####)
> GET /etc/passwd HTTP/1.1
> User-Agent: FOO
> Host: LOCALHOST:44323
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Content-Length: 40
< Access-Control-Allow-Origin: *
< Content-Type: text/plain
< Date: DATE
<
{ [data not shown]
* Connection #### to host LOCALHOST left intact
PMWEBD error, XXX

* About to connect() to LOCALHOST port 44323 (####)
*   Trying LOCALADDR...
* Connected to LOCALHOST (LOCALADDR) port 44323 (####)
> GET /graphite/render?target=* HTTP/1.1
> User-Agent: FOO
> Host: LOCALHOST:44323
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Content-Length: 40
< Access-Control-Allow-Origin: *
< Content-Type: text/plain
< Date: DATE
<
{ [data not shown]
* Connection #### to host LOCALHOST left intact
PMWEBD error, XXX

file service ok
